### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Mmyyo** [jgernandt/blender-hkx#1]
Using the "Install" button to select "Blender-hkX-main.zip" has no effect. Is there something wrong with my installation ？

**Comment by Mmyyo** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\io_hkx_animation\__init__.py", line 1, in <module>
    import io_hkx_animation.hkx_export
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\io_hkx_animation\hkx_export.py", line 33, in <module>
    class ActionGenerator(xml.sax.saxutils.XMLGenerator):
AttributeError: module 'xml' has no attribute 'sax'

**Comment by jgernandt** [comment]
There is no working release yet. This is an experimental project that I started just a couple of days ago.

**Comment by Mmyyo** [comment]
Oh, thanks for your reply. Looking forward to your official release.

**Comment by Bromancelot** [comment]
> There is no working release yet. This is an experimental project that I started just a couple of days ago.

Not sure if it's on your to-do list or if someone has brought it up to you already, but please please _**please**_ include what version of Blender you are planning to make this add-on for. As well as what version of Blender _**you**_ are using to test your add-on. Saves us all(/including yourself) alot of trouble down the line in terms of troubleshooting. 
(Each version of Blender has been very picky when it comes to add-ons for previous/future versions)

I'm excited to see what you come up with. I deep dived into this a few years ago and gave, so good luck!

**Comment by jgernandt** [comment]
I've included the Blender version in the description.

As it stands right now, the addon works as intended, but I can't share a functional version due to Havok licensing.
